### ISSUE TITLE
Latest Windows Build Crash, Server and Client

### ISSUE THREAD

**Issue by danyul0w0** [Razish/japp#361] opened 2016-01-13 16:29 UTC
Using the latest OpenJK and JA++ build, neither client nor server function;

```========================================
             JA++ Crash Log
========================================
Version: JA++, 32 bits, Jan 13 2016, d49ab9e* (Windows)
Side: Server-side
Build Date/Time: Jan 13 2016 19:42:42
Operating system: Microsoft Unknown Edition (build 9200), 64-bit
Crash type: Exception

----------------------------------------
          Exception Information
----------------------------------------
Process: C:\Program Files (x86)\Steam\steamapps\common\Jedi Academy\GameData\openjkded.x86.exe
Exception in module: msvcrt.dll
Exception Address: 0x77688FCC (msvcrt.dll+0x88FCC)
Exception Code: 0xC0000005 (Access Violation)
Attempted to read data at: 0x00000001

----------------------------------------
              Register Dump
----------------------------------------
General Purpose & Control Registers:
EAX: 0x001A9894, EBX: 0x00000001, ECX: 0x00000001, EDX: 0xFFFFFFFE
EDI: 0x08483AA8, ESI: 0x08483AA8, ESP: 0x001A977C, EBP: 0x08483AA9
EIP: 0x77688FCC

Segment Registers:
CS: 0x00000023, DS: 0x0000002B, ES: 0x0000002B
FS: 0x00000053, GS: 0x0000002B, SS: 0x0000002B

----------------------------------------
               Module List
----------------------------------------
0x00200000 - openjkded.x86 - C:\Program Files (x86)\Steam\steamapps\common\Jedi Academy\GameData\openjkded.x86.exe
0x77750000 - ntdll - C:\WINDOWS\SYSTEM32\ntdll.dll
0x76400000 - KERNEL32 - C:\WINDOWS\SYSTEM32\KERNEL32.DLL
0x77480000 - KERNELBASE - C:\WINDOWS\SYSTEM32\KERNELBASE.dll
0x74D60000 - SHELL32 - C:\WINDOWS\SYSTEM32\SHELL32.dll
0x77600000 - msvcrt - C:\WINDOWS\SYSTEM32\msvcrt.dll
0x764E0000 - cfgmgr32 - C:\WINDOWS\SYSTEM32\cfgmgr32.dll
0x74640000 - windows.storage - C:\WINDOWS\SYSTEM32\windows.storage.dll
0x77120000 - combase - C:\WINDOWS\SYSTEM32\combase.dll
0x76190000 - RPCRT4 - C:\WINDOWS\SYSTEM32\RPCRT4.dll
0x74480000 - SspiCli - C:\WINDOWS\SYSTEM32\SspiCli.dll
0x74470000 - CRYPTBASE - C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
0x76570000 - bcryptPrimitives - C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll
0x74D10000 - sechost - C:\WINDOWS\SYSTEM32\sechost.dll
0x74500000 - advapi32 - C:\WINDOWS\SYSTEM32\advapi32.dll
0x74B90000 - shlwapi - C:\WINDOWS\SYSTEM32\shlwapi.dll
0x76640000 - GDI32 - C:\WINDOWS\SYSTEM32\GDI32.dll
0x772E0000 - USER32 - C:\WINDOWS\SYSTEM32\USER32.dll
0x76180000 - kernel.appcore - C:\WINDOWS\SYSTEM32\kernel.appcore.dll
0x74C80000 - shcore - C:\WINDOWS\SYSTEM32\shcore.dll
0x77430000 - powrprof - C:\WINDOWS\SYSTEM32\powrprof.dll
0x76300000 - profapi - C:\WINDOWS\SYSTEM32\profapi.dll
0x738C0000 - WSOCK32 - C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x6F120000 - WINMM - C:\WINDOWS\SYSTEM32\WINMM.dll
0x6AA70000 - MSVCR120 - C:\Program Files (x86)\Steam\steamapps\common\Jedi Academy\GameData\MSVCR120.dll
0x745E0000 - WS2_32 - C:\WINDOWS\SYSTEM32\WS2_32.dll
0x6CD20000 - MSVCP120 - C:\Program Files (x86)\Steam\steamapps\common\Jedi Academy\GameData\MSVCP120.dll
0x00D50000 - WINMMBASE - C:\WINDOWS\SYSTEM32\WINMMBASE.dll
0x74B40000 - IMM32 - C:\WINDOWS\SYSTEM32\IMM32.DLL
0x73800000 - CRYPTSP - C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x737D0000 - rsaenh - C:\WINDOWS\system32\rsaenh.dll
0x73ED0000 - bcrypt - C:\WINDOWS\SYSTEM32\bcrypt.dll
0x69930000 - napinsp - C:\WINDOWS\system32\napinsp.dll
0x69910000 - pnrpnsp - C:\WINDOWS\system32\pnrpnsp.dll
0x69950000 - NLAapi - C:\WINDOWS\system32\NLAapi.dll
0x74320000 - mswsock - C:\WINDOWS\System32\mswsock.dll
0x709A0000 - DNSAPI - C:\WINDOWS\SYSTEM32\DNSAPI.dll
0x762F0000 - NSI - C:\WINDOWS\SYSTEM32\NSI.dll
0x6EDA0000 - winrnr - C:\WINDOWS\System32\winrnr.dll
0x70970000 - mdnsNSP - C:\Program Files (x86)\Bonjour\mdnsNSP.dll
0x742F0000 - Iphlpapi - C:\WINDOWS\SYSTEM32\Iphlpapi.DLL
0x698F0000 - wshbth - C:\WINDOWS\System32\wshbth.dll
0x70910000 - fwpuclnt - C:\WINDOWS\System32\fwpuclnt.dll
0x70960000 - rasadhlp - C:\Windows\System32\rasadhlp.dll
0x08250000 - OJK819D - C:\Users\Daniel\AppData\Local\Temp\OJK819D.tmp
0x76970000 - PSAPI - C:\WINDOWS\SYSTEM32\PSAPI.DLL
0x70290000 - dbghelp - C:\WINDOWS\SYSTEM32\dbghelp.dll

----------------------------------------
          Disassembly/Source code
----------------------------------------
Crash location located at 0x77688FCC: msvcrt.dll::strlen(+0xC) [Func at 0x77688FC0]
No source code information available

^^^^^^^^^^
0x77688FB9 - int3                          
0x77688FBA - int3                          
0x77688FBB - int3                          
0x77688FBC - int3                          
0x77688FBD - int3                          
0x77688FBE - int3                          
0x77688FBF - int3                          
0x77688FC0 - mov ecx, [esp+0x4]            
0x77688FC4 - test ecx, 0x3                 
0x77688FCA - jz short 0x77688ff0            (strlen+0x30)

=============================================
0x77688FCC - mov al, [ecx]                  <-- Exception
=============================================

0x77688FCE - add ecx, 0x1                  
0x77688FD1 - test al, al                   
0x77688FD3 - jz short 0x77689023            (strlen+0x63)
0x77688FD5 - test ecx, 0x3                 
0x77688FDB - jnz 0x77688fcc                 (strlen+0xC)
0x77688FDD - add eax, 0x0                  
0x77688FE2 - lea esp, [esp+0x0]            
0x77688FE9 - lea esp, [esp+0x0]            
0x77688FF0 - mov eax, [ecx]                
0x77688FF2 - mov edx, 0x7efefeff           
vvvvvvvvvv

----------------------------------------
                Backtrace
----------------------------------------
msvcrt.dll::strlen(+0xC) [0x77688FCC]

----------------------------------------
            Extra Information
----------------------------------------
----------------------------------------
          Server info / players
----------------------------------------
Map: mp/ffa3

Players: 0/18:

========================================
             End of crash log
========================================
```

Same error on Client, bar the server info.

**Comment by ensiform** [comment] 2016-01-13 20:23
Which build last worked?

**Comment by danyul0w0** [comment] 2016-01-13 20:59
I was running December build prior to this.

**Comment by ensiform** [comment] 2016-01-13 21:36
It looks like there's no symbols and could possibly be in openjk.

**Comment by Razish** [comment] 2016-01-14 05:46
I will try updating OpenJK and confirming while I'm still on Windows.

**Comment by danyul0w0** [comment] 2016-01-14 09:42
Reporting back a little, I've gone ahead and done some testing. First off, yeah I'm Unbekannter from EFF c:

I have done the following steps to remedy this; Fresh OpenJK install folder with flushed documents versions of configs, no custom PK3 apart from JA++ with base assets. Same with actual installation folder. Both still reproduce the error, on the OpenJK builds dated 11th January, 4th January and 21st December.

All these things were tested on Windows 10 64 bit. I'm currently reverifying my disk images to ensure it's not a corruption in Windows.

I can confirm that the previous JA++ works on all three, (the December 17th build of JA++)

**Comment by EpicLoyd** [comment] 2016-01-14 12:37
my friend also confirmed dat error

**Comment by Razish** [comment] 2016-01-14 13:28
Is this related to W10? or a popular mod used?

**Comment by ensiform** [comment] 2016-01-14 14:48
Well I'm trying to figure out where strlen is being used that it could have crashed :\  Assuming that its the same symbol every time?

**Comment by Razish** [comment] 2016-01-14 15:03
@danyul0w0 could you try compiling a debug build of both JA++ and OpenJK?
It looks like the JA++ compilation instructions are out of date - it requires Python 2.7.10 64 bit, TDM-GCC-64. Run `scons debug=1 force32=1` from src directory and it should just work. assuming Python and TDM-GCC-64 are in your `%PATH%` envvar.

**Comment by Dexter4637** [comment] 2016-01-14 17:04
@Razish 
I cant compile ja++ , Python and TDM-GCC-64 are installed and i added this to %Path% . See here: http://prntscr.com/9q2b0y

**Comment by Razish** [comment] 2016-01-14 17:23
Oh, it needs a patch to Python core libraries on Windows. Catch me on Steam, IRC or something and I can guide you through it before fixing the compilation instructions on the site

**Comment by Dexter4637** [comment] 2016-01-14 18:37
it seems to be an assets problem, newest ja++ works with older assets, with the latest assets i got the client crash

**Comment by Razish** [comment] 2016-01-15 05:55
Should be fixed in https://github.com/Razish/japp-assets/commit/ce41e4b2c0ff0d4885d9c11135517bfcabf53222

**Comment by Dexter4637** [comment] 2016-01-15 12:30
@Razish jup, fixed.

**Comment by EpicLoyd** [comment] 2016-01-15 13:20
so, what caused that crash?

**Comment by Razish** [comment] 2016-01-16 03:47
Requiring a file that wasnt packaged

**Closed by Razish** 2016-01-16 03:47 UTC

**Comment by EpicLoyd** [comment] 2016-01-16 07:21
lol, it should tell us that file not exist, not crash whole game, isn't it?

**Comment by Razish** [comment] 2016-01-16 14:32
Yeah, I may investigate more when I'm back home, but for now at-least people aren't crashing
